// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUDYGClhOghkRyGiJAdNoTQK-28v-78xU',
    appId: '1:762533539097:web:d564a5e05eaa5f1fe42988',
    messagingSenderId: '762533539097',
    projectId: 'pmobprak-cb0d8',
    authDomain: 'pmobprak-cb0d8.firebaseapp.com',
    storageBucket: 'pmobprak-cb0d8.appspot.com',
    measurementId: 'G-K4HEV5VY6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQpJ_ipSvyCGEWy1RNPQWj5To96MI4IE0',
    appId: '1:762533539097:android:46f0e2ffcb65bccbe42988',
    messagingSenderId: '762533539097',
    projectId: 'pmobprak-cb0d8',
    storageBucket: 'pmobprak-cb0d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaN-fahUNa6ULwmyM9s_H6QD-27P1nn3o',
    appId: '1:762533539097:ios:9699596b4a2b5e8ae42988',
    messagingSenderId: '762533539097',
    projectId: 'pmobprak-cb0d8',
    storageBucket: 'pmobprak-cb0d8.appspot.com',
    iosBundleId: 'com.example.pmobprak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaN-fahUNa6ULwmyM9s_H6QD-27P1nn3o',
    appId: '1:762533539097:ios:9747409e3902da82e42988',
    messagingSenderId: '762533539097',
    projectId: 'pmobprak-cb0d8',
    storageBucket: 'pmobprak-cb0d8.appspot.com',
    iosBundleId: 'com.example.pmobprak.RunnerTests',
  );
}
